const constants = {

    //customer
    ADD_CUSTOMER: 'ADD_CUSTOMER',
    UPDATE_CUSTOMER_PROPERTY: 'UPDATE_CUSTOMER_PROPERTY',

    //inventory
    SET_INVENTORY_COUNT: 'SET_INVENTORY_COUNT',
    UPDATE_NEEDED_PROPERTY: 'UPDATE_NEEDED_PROPERTY',
    UPDATE_SUBTOTAL: 'UPDATE_SUBTOTAL',
    UPDATE_AVAILABILITY: 'UPDATE_AVAILABILITY',
    RESET_AVAILABILITY: 'RESET_AVAILABILITY',

    //time
    SET_TIME: 'SET_TIME',

    //order
    GET_CUSTOMER: 'GET_CUSTOMER'
}

export default constants