const constants = {

    //customer
    ADD_CUSTOMER: 'ADD_CUSTOMER',
    ARCHIVE_CUSTOMER: 'ARCHIVE_CUSTOMER',
    UPDATE_CUSTOMER_PROPERTY: 'UPDATE_CUSTOMER_PROPERTY',
    REMOVE_CUSTOMER: 'REMOVE_CUSTOMER',

    //inventory
    SET_INVENTORY_COUNT: 'SET_INVENTORY_COUNT',
    UPDATE_NEEDED_PROPERTY: 'UPDATE_NEEDED_PROPERTY',
    UPDATE_SUBTOTAL: 'UPDATE_SUBTOTAL',
    UPDATE_AVAILABILITY: 'UPDATE_AVAILABILITY',
    RESET_AVAILABILITY: 'RESET_AVAILABILITY',
    RETURN_ITEMS: 'RETURN_ITEMS',

    //time
    SET_TIME: 'SET_TIME',

    //orders


}

export default constants