const constants = {
    ADD_CUSTOMER: 'ADD_CUSTOMER',
    UPDATE_FIRST_NAME: 'UPDATE_FIRST_NAME',
    UPDATE_LAST_NAME: 'UPDATE_LAST_NAME',
    UPDATE_PHONE_NUMBER: 'UPDATE_PHONE_NUMBER',
    UPDATE_EMAIL_ADDRESS: 'UPDATE_EMAIL_ADDRESS',
    UPDATE_STREET_ADDRESS: 'UPDATE_STREET_ADDRESS',
    UPDATE_CITY: 'UPDATE_CITY',
    UPDATE_US_STATE: 'UPDATE_US_STATE',
    UPDATE_ZIP_CODE: 'UPDATE_ZIP_CODE',
    SET_CURRENT_CUSTOMER: 'SET_CURRENT_CUSTOMER',
}

export default constants